import mods.modularmachinery.RecipeBuilder;
import crafttweaker.oredict.IOreDictEntry;
import crafttweaker.oredict.IOreDict;
import crafttweaker.liquid.ILiquidStack;
import crafttweaker.item.IIngredient;

val thorium_oxi = RecipeBuilder.newBuilder("thorium_oxi", "silex", 1200);
thorium_oxi.addItemInput(<nuclearcraft:depleted_fuel_thorium:1> * 9);
thorium_oxi.addItemInput(<contenttweaker:laser_crystal_co2> * 1);
thorium_oxi.addFluidInput(<liquid:hydrogen_peroxide> * 1000);
thorium_oxi.addItemOutput(<nuclearcraft:uranium:2> * 1);
thorium_oxi.addItemOutput(<nuclearcraft:uranium:12> * 5);
thorium_oxi.addItemOutput(<nuclearcraft:fission_dust:5> * 1).setChance(0.25);
thorium_oxi.addItemOutput(<nuclearcraft:neptunium:2> * 1);
thorium_oxi.addItemOutput(<nuclearcraft:neptunium:7> * 1);
thorium_oxi.addItemOutput(<nuclearcraft:fission_dust:8> * 1).setChance(0.25);
thorium_oxi.addItemOutput(<contenttweaker:laser_crystal_co2> * 1);
thorium_oxi.addMekanismLaserInput(24000);
thorium_oxi.build();

val thorium_nit = RecipeBuilder.newBuilder("thorium_nit", "silex", 1200);
thorium_nit.addItemInput(<nuclearcraft:depleted_fuel_thorium:1> * 9);
thorium_nit.addItemInput(<contenttweaker:laser_crystal_co2> * 1);
thorium_nit.addFluidInput(<liquid:hydrogen_peroxide> * 1000);
thorium_nit.addItemOutput(<nuclearcraft:uranium:3> * 1);
thorium_nit.addItemOutput(<nuclearcraft:uranium:13> * 5);
thorium_nit.addItemOutput(<nuclearcraft:fission_dust:5> * 1).setChance(0.25);
thorium_nit.addItemOutput(<nuclearcraft:neptunium:3> * 1);
thorium_nit.addItemOutput(<nuclearcraft:neptunium:8> * 1);
thorium_nit.addItemOutput(<nuclearcraft:fission_dust:8> * 1).setChance(0.25);
thorium_nit.addItemOutput(<contenttweaker:laser_crystal_co2> * 1);
thorium_nit.addMekanismLaserInput(27000);
thorium_nit.build();

val thorium_zir = RecipeBuilder.newBuilder("thorium_zir", "silex", 1200);
thorium_zir.addItemInput(<nuclearcraft:depleted_fuel_thorium:1> * 9);
thorium_zir.addItemInput(<contenttweaker:laser_crystal_co2> * 1);
thorium_zir.addFluidInput(<liquid:hydrogen_peroxide> * 1000);
thorium_zir.addItemOutput(<nuclearcraft:uranium:4> * 1);
thorium_zir.addItemOutput(<nuclearcraft:uranium:14> * 5);
thorium_zir.addItemOutput(<nuclearcraft:fission_dust:5> * 1).setChance(0.25);
thorium_zir.addItemOutput(<nuclearcraft:neptunium:4> * 1);
thorium_zir.addItemOutput(<nuclearcraft:neptunium:9> * 1);
thorium_zir.addItemOutput(<nuclearcraft:fission_dust:8> * 1).setChance(0.25);
thorium_zir.addItemOutput(<nuclearcraft:dust:10> * 1);
thorium_zir.addItemOutput(<contenttweaker:laser_crystal_co2> * 1);
thorium_zir.addMekanismLaserInput(28500);
thorium_zir.build();

val uranium_oxi = RecipeBuilder.newBuilder("uranium_oxi", "silex", 1200);
uranium_oxi.addItemInput(<nuclearcraft:depleted_fuel_uranium:1> * 9);
uranium_oxi.addItemInput(<contenttweaker:laser_crystal_co2> * 1);
uranium_oxi.addFluidInput(<liquid:hydrogen_peroxide> * 1000);
uranium_oxi.addItemOutput(<nuclearcraft:plutonium:12> * 1);
uranium_oxi.addItemOutput(<nuclearcraft:uranium:12> * 5);
uranium_oxi.addItemOutput(<nuclearcraft:fission_dust:5> * 1).setChance(0.25);
uranium_oxi.addItemOutput(<nuclearcraft:plutonium:17> * 1);
uranium_oxi.addItemOutput(<nuclearcraft:americium:12> * 1);
uranium_oxi.addItemOutput(<nuclearcraft:fission_dust:8> * 1).setChance(0.25);
uranium_oxi.addItemOutput(<contenttweaker:laser_crystal_co2> * 1);
uranium_oxi.addMekanismLaserInput(34900);
uranium_oxi.build();

val uranium_nit = RecipeBuilder.newBuilder("uranium_nit", "silex", 1200);
uranium_nit.addItemInput(<nuclearcraft:depleted_fuel_uranium:2> * 9);
uranium_nit.addItemInput(<contenttweaker:laser_crystal_co2> * 1);
uranium_nit.addFluidInput(<liquid:hydrogen_peroxide> * 1000);
uranium_nit.addItemOutput(<nuclearcraft:plutonium:13> * 1);
uranium_nit.addItemOutput(<nuclearcraft:uranium:13> * 5);
uranium_nit.addItemOutput(<nuclearcraft:fission_dust:5> * 1).setChance(0.25);
uranium_nit.addItemOutput(<nuclearcraft:plutonium:18> * 1);
uranium_nit.addItemOutput(<nuclearcraft:americium:13> * 1);
uranium_nit.addItemOutput(<nuclearcraft:fission_dust:8> * 1).setChance(0.25);
uranium_nit.addItemOutput(<contenttweaker:laser_crystal_co2> * 1);
uranium_nit.addMekanismLaserInput(37800);
uranium_nit.build();

val uranium_zir = RecipeBuilder.newBuilder("uranium_zir", "silex", 1200);
uranium_zir.addItemInput(<nuclearcraft:depleted_fuel_uranium:3> * 9);
uranium_zir.addItemInput(<contenttweaker:laser_crystal_co2> * 1);
uranium_zir.addFluidInput(<liquid:hydrogen_peroxide> * 1000);
uranium_zir.addItemOutput(<nuclearcraft:plutonium:14> * 1);
uranium_zir.addItemOutput(<nuclearcraft:uranium:14> * 5);
uranium_zir.addItemOutput(<nuclearcraft:fission_dust:5> * 1).setChance(0.25);
uranium_zir.addItemOutput(<nuclearcraft:plutonium:19> * 1);
uranium_zir.addItemOutput(<nuclearcraft:americium:14> * 1);
uranium_zir.addItemOutput(<nuclearcraft:fission_dust:8> * 1).setChance(0.25);
uranium_zir.addItemOutput(<nuclearcraft:dust:10> * 1);
uranium_zir.addItemOutput(<contenttweaker:laser_crystal_co2> * 1);
uranium_zir.addMekanismLaserInput(38900);
uranium_zir.build();

val uranium_oxi2 = RecipeBuilder.newBuilder("uranium_oxi2", "silex", 1200);
uranium_oxi2.addItemInput(<nuclearcraft:depleted_fuel_uranium:5> * 9);
uranium_oxi2.addItemInput(<contenttweaker:laser_crystal_co2> * 1);
uranium_oxi2.addFluidInput(<liquid:hydrogen_peroxide> * 1000);
uranium_oxi2.addItemOutput(<nuclearcraft:plutonium:17> * 3);
uranium_oxi2.addItemOutput(<nuclearcraft:uranium:7> * 1);
uranium_oxi2.addItemOutput(<nuclearcraft:uranium:12> * 2);
uranium_oxi2.addItemOutput(<nuclearcraft:fission_dust:5> * 1).setChance(0.75);
uranium_oxi2.addItemOutput(<nuclearcraft:americium:12> * 1);
uranium_oxi2.addItemOutput(<nuclearcraft:fission_dust:8> * 1).setChance(0.75);
uranium_oxi2.addItemOutput(<contenttweaker:laser_crystal_co2> * 1);
uranium_oxi2.addMekanismLaserInput(44900);
uranium_oxi2.build();

val uranium_nit2 = RecipeBuilder.newBuilder("uranium_nit2", "silex", 1200);
uranium_nit2.addItemInput(<nuclearcraft:depleted_fuel_uranium:4> * 9);
uranium_nit2.addItemInput(<contenttweaker:laser_crystal_co2> * 1);
uranium_nit2.addFluidInput(<liquid:hydrogen_peroxide> * 1000);
uranium_nit2.addItemOutput(<nuclearcraft:plutonium:18> * 3);
uranium_nit2.addItemOutput(<nuclearcraft:uranium:8> * 1);
uranium_nit2.addItemOutput(<nuclearcraft:uranium:13> * 2);
uranium_nit2.addItemOutput(<nuclearcraft:fission_dust:5> * 1).setChance(0.75);
uranium_nit2.addItemOutput(<nuclearcraft:americium:13> * 1);
uranium_nit2.addItemOutput(<nuclearcraft:fission_dust:8> * 1).setChance(0.75);
uranium_nit2.addItemOutput(<contenttweaker:laser_crystal_co2> * 1);
uranium_nit2.addMekanismLaserInput(47800);
uranium_nit2.build();

val uranium_zir2 = RecipeBuilder.newBuilder("uranium_zir2", "silex", 1200);
uranium_zir2.addItemInput(<nuclearcraft:depleted_fuel_uranium:4> * 9);
uranium_zir2.addItemInput(<contenttweaker:laser_crystal_co2> * 1);
uranium_zir2.addFluidInput(<liquid:hydrogen_peroxide> * 1000);
uranium_zir2.addItemOutput(<nuclearcraft:plutonium:19> * 3);
uranium_zir2.addItemOutput(<nuclearcraft:uranium:9> * 1);
uranium_zir2.addItemOutput(<nuclearcraft:uranium:14> * 2);
uranium_zir2.addItemOutput(<nuclearcraft:fission_dust:5> * 1).setChance(0.75);
uranium_zir2.addItemOutput(<nuclearcraft:americium:14> * 1);
uranium_zir2.addItemOutput(<nuclearcraft:fission_dust:8> * 1).setChance(0.75);
uranium_zir2.addItemOutput(<contenttweaker:laser_crystal_co2> * 1);
uranium_zir2.addItemOutput(<nuclearcraft:dust:10> * 2);
uranium_zir2.addMekanismLaserInput(48900);
uranium_zir2.build();

